# Generated by Django 4.2.11 on 2026-02-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("lease", "Lease"),
                            ("siteVisit", "Site Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("schedule", "Schedule"),
                            ("converted", "Converted"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=30)),
                ("client_phone", models.CharField(max_length=15, unique=True)),
                ("client_email", models.EmailField(max_length=254)),
                ("lead_type", models.CharField(max_length=30)),
                ("preferred_location", models.CharField(max_length=150)),
                ("budget_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("budget_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_preferred_property",
                        to="core.propertytype",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_source_channel",
                        to="core.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("siteVisitDone", "Site visit Done"),
                            ("negotiations", "Negotiations"),
                            ("offerMade", "Offer Made"),
                            ("dueDiligence", "Due Diligence"),
                            ("contractSigned", "Contract Signed"),
                            ("closedWon", "Closed Won"),
                            ("closedLost", "Closed Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "expected_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("agreed_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expected_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("closing_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_case_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resulted_from_lead",
                        to="sales.lead",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry",
                        to="sales.inquiry",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleClosure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("closing_date", models.DateField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("won", "Won"), ("lost", "Lost")], max_length=20
                    ),
                ),
                ("lose_reason", models.TextField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        max_length=30,
                    ),
                ),
                ("documents_completed", models.BooleanField()),
                ("document", models.URLField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer_name", models.CharField(max_length=30)),
                ("referrer_phone", models.CharField(max_length=10)),
                ("referrer_email", models.EmailField(max_length=30)),
                ("referred_client_name", models.CharField(max_length=30)),
                ("referred_client_phone", models.CharField(max_length=10)),
                ("referrer_client_email", models.EmailField(max_length=30)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(auto_now=True)),
                (
                    "referrer_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referring",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_sales_case",
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostSaleTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("titleTransfer", "Title Transfer"),
                            ("handOver", "Hand Over"),
                            ("commissionPayment", "Commission Payment "),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("inProgress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_closure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.saleclosure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offered_date", models.DateTimeField(auto_now=True)),
                ("expiry_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "made_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_made_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_for_sales_case",
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inquiry",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquired_from_lead",
                to="sales.lead",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_inquired",
                to="properties.property",
            ),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_up_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsApp", "Whats App"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField()),
                ("next_action", models.TextField()),
                ("next_action_date", models.DateField()),
                ("completed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_up_for_sales_case",
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
    ]
