# Generated by Django 4.2.11 on 2026-02-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="year_built",
            field=models.DateField(blank=True, null=True),
        ),
    ]
