# Generated by Django 6.0 on 2026-01-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mediaAndMarketing", "0001_initial"),
        ("sales", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("transport", "Transport"),
                            ("legal", "Legal"),
                            ("site_visit", "Site Visit"),
                            ("operations", "operations"),
                            ("salaries", "Salaries"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mpesa", "Mpesa"),
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_ref", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to="users.user",
                    ),
                ),
                (
                    "paid_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_to",
                        to="users.user",
                    ),
                ),
                (
                    "related_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign",
                        to="mediaAndMarketing.campaign",
                    ),
                ),
                (
                    "related_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_case",
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("commission", "Commission"),
                            ("referralFee", "Referral Fee"),
                        ],
                        default="commission",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KSH", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("invoiced", "Invoiced"),
                            ("received", "Received"),
                            ("canceled", "Canceled"),
                        ],
                        default="expected",
                        max_length=30,
                    ),
                ),
                ("reference_number", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField()),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_from_sales_case",
                        to="sales.salescase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
