# Generated by Django 4.2.11 on 2026-02-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="sales_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenue_from_sales_case",
                to="sales.salescase",
            ),
        ),
    ]
