# Generated by Django 4.2.11 on 2026-02-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("core", "0001_initial"),
        ("mediaAndMarketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialpost",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_posts",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="social_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="mediaAndMarketing.socialchannel",
            ),
        ),
        migrations.AddField(
            model_name="socialchannel",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_contents",
                to="core.channel",
            ),
        ),
        migrations.AddField(
            model_name="newsletterlog",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="mediaAndMarketing.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="mediaAndMarketing.campaign",
            ),
        ),
    ]
