# Generated by Django 4.2.11 on 2026-02-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("buyer", "Buyer"),
                            ("broker", "Broker"),
                            ("owner", "Owner"),
                            ("referralAgent", "Referral Agent"),
                            ("partner", "Partner"),
                            ("finance", "Finance"),
                            ("SalesAndMarketing", "Sales And Marketing"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("total_referrals", models.IntegerField(default=0)),
                ("successful_referrals", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_agents",
                        to="users.user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_referral_agents",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("inspection", "Inspection"),
                            ("valuation", "Valuation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("services_offered", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="users.user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_partners",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        max_length=50,
                    ),
                ),
                ("total_properties", models.IntegerField(default=0)),
                ("active_properties", models.IntegerField(default=0)),
                ("sold_properties", models.IntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.relationshipstatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="users.user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_owners",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("address", models.TextField()),
                ("website", models.URLField(blank=True, null=True)),
                ("profile_description", models.TextField(blank=True, null=True)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("project_count", models.IntegerField(default=0)),
                ("completed_projects", models.IntegerField(default=0)),
                ("ongoing_projects", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="users.owner",
                    ),
                ),
                (
                    "property_types",
                    models.ManyToManyField(
                        related_name="companies", to="core.propertytype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_preferences", models.TextField()),
                ("budget_range_min", models.CharField(max_length=50)),
                ("budget_range_max", models.CharField(max_length=50)),
                ("urgency_level", models.CharField(max_length=50)),
                ("min_land_size", models.FloatField()),
                ("max_land_size", models.FloatField()),
                ("house_size", models.FloatField()),
                ("house_bedrooms_min", models.IntegerField()),
                ("house_bedrooms_max", models.IntegerField()),
                ("house_bathrooms_min", models.IntegerField()),
                ("house_bathrooms_max", models.IntegerField()),
                ("conversion_stage", models.CharField(max_length=50)),
                ("last_contacted", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "preferred_channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Channel",
                        to="core.channel",
                    ),
                ),
                (
                    "preferred_property_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.propertytype",
                    ),
                ),
                (
                    "preferred_use",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.propertyuse",
                    ),
                ),
                (
                    "relationship_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.relationshipstatus",
                    ),
                ),
                (
                    "source_of_lead",
                    models.ForeignKey(
                        default="field",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="lead_source",
                        to="core.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "broker_type",
                    models.CharField(
                        choices=[("independent", "Independent"), ("agency", "Agency")],
                        max_length=50,
                    ),
                ),
                ("years_of_experience", models.IntegerField()),
                ("areas_of_expertise", models.TextField()),
                ("primary_location", models.CharField(max_length=100)),
                ("service_areas", models.TextField()),
                ("bio", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("active_listings", models.IntegerField(default=0)),
                ("total_listings", models.IntegerField(default=0)),
                ("total_sales", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("id_document", models.URLField(blank=True, null=True)),
                ("kra_documents", models.URLField(blank=True, null=True)),
                ("agreement_signed", models.BooleanField(default=False)),
                ("agreement_document", models.URLField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("public_slug", models.SlugField(unique=True)),
                (
                    "relationship_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.relationshipstatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokers",
                        to="users.user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_brokers",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
