# Generated by Django 4.2.11 on 2026-02-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_created=True)),
                ("created_at", models.DateTimeField(auto_created=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("siteVisit", "Site Visit"),
                            ("landSearch", "Land search"),
                            ("dealClosing", "Deal Closing"),
                            ("inspection", "Inspection"),
                            ("meeting", "Meeting"),
                            ("call", "Call"),
                            ("virtualTour", "Virtual Tour"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.TextField()),
                ("scheduled_at", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("location", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("canceled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("noShow", "No Show"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("notInterested", "Not Interested"),
                            ("needFollowUp", "Need Follow Up"),
                            ("offerMade", "Offer Made"),
                            ("dealClosed", "Deal Closed"),
                            ("dealLost", "Deal Lost"),
                        ],
                        default="interested",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_conductor",
                        to="users.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_creator",
                        to="users.user",
                    ),
                ),
                (
                    "sales_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SalesCase",
                        to="sales.salescase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_name", models.CharField(max_length=150)),
                ("participant_phone", models.CharField(max_length=10)),
                ("participant_email", models.CharField(max_length=150)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Appointment",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Participant",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
